// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Readconf() {
  return window['go']['main']['App']['Readconf']();
}

export function Writeconf(arg1) {
  return window['go']['main']['App']['Writeconf'](arg1);
}


export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

