// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetServers():Promise<main.Message>;

export function Greet(arg1:string):Promise<string>;

export function Readconf():Promise<string>;

export function Writeconf(arg1:string):Promise<void>;
